name: Build Frontend

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

defaults:
  run:
    working-directory: frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pre-setup
        uses: F201/ASELab-dashboard/.github/workflows/common.yml@main


      - name: Build Frontend
        run: npm run build --if-present